post/urls.py
from django.urls import path
from . import views

app_name = 'postApp'

urlpatterns = [
    path('<int:id>/<str:slug>/', views.postDetail.as_view(), name='postDetail')
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include(('post.urls', 'app_name'), namespace='PostApplication')),
    path('newsletter/', include(('newsletter.urls', 'app_name'), namespace='NewsletterApplication')),
    path('', views.homePage.as_view(), name="HomepageApplication"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/models.py
from django.db import models
from django.urls import reverse
from account.models import User


class Tag(models.Model):
    title=models.CharField(max_length=100, unique=True)
    
    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})   # the "_detail" is a name pattern defined inside the url associating to a post-tag-detail.


class Category(models.Model):
    title=models.CharField(max_length=100)
    metaTitle=models.CharField(max_length=100)
    slug=models.SlugField(max_length=100)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("_detail", kwargs={"pk": self.pk})   # the "_detail" is a name pattern defined inside the url associating to a post-category-detail.


POST_STATUS_CHOICES = [
    ("DRAFT", "Draft"),
    ("PUBLISHED", "Published"),
    ("ARCHIVED", "Archived"),
]

class Post(models.Model):
    title=models.CharField(max_length=255)
    metaTitle=models.CharField(max_length=255)
    slug=models.SlugField(max_length=255, unique=True)
    summary=models.TextField()
    status=models.CharField(max_length=9, choices=POST_STATUS_CHOICES, default="PUBLISHED")
    # isPublished=models.BooleanField(default=False)
    feature_image = models.ImageField(upload_to='blog/', verbose_name='Add Feature Image', blank=True, null=True)
    published_at=models.DateTimeField(auto_now_add=True)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    content=models.TextField()
    author=models.ForeignKey(User, on_delete=models.CASCADE, related_name="post")
    tag=models.ManyToManyField(Tag)
    category=models.ManyToManyField(Category)

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"
    
    def __str__(self):
        return self.title


class PostMeta(models.Model):
    key=models.CharField(max_length=30)
    content=models.TextField()
    post=models.ForeignKey(Post, on_delete=models.CASCADE, related_name="meta")

    class Meta:
        verbose_name = "Post Meta"
        verbose_name_plural = "Post Meta"


class Comments(models.Model):
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    isPublished=models.BooleanField(default=False)
    published_at=models.DateTimeField(auto_now_add=True)
    post=models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comment")

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"


class TrendingPost(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE, related_name="trendingPost")
    created_at=models.DateTimeField(auto_now_add=True)


class LatestPost(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE, related_name="latestPost")
    created_at=models.DateTimeField(auto_now_add=True)


class MostPopularPost(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE, related_name="mostPopularPost")
    created_at=models.DateTimeField(auto_now_add=True)


class RelatedPost(models.Model):
    post=models.ForeignKey(Post, on_delete=models.SET_NULL, null=True, related_name="originalPost")
    relatedPost=models.ForeignKey(Post, on_delete=models.SET_NULL, null=True, related_name="relatedPost")
    created_at=models.DateTimeField(auto_now_add=True)

post/views.py
from django.shortcuts import render, HttpResponse
from django.views import View
from post.models import Post, RelatedPost

class postDetail(View):

    template_name = 'post/postDetail.html'

    def get(self, request, id, slug):
        post = Post.objects.get(id=id)
        relatedPost = RelatedPost.objects.filter(post=post)
        context = {
            'post': post,
            'relatedPost': relatedPost,
        }
        return render(request, self.template_name, context=context)
    

templates/post/postDetail.html
<!DOCTYPE html>
{% extends 'layout/base.html' %}
{% load static %}

{% block css %}
<link id="pagestyle" href="{% static 'css/output/post/postDetail.css' %}" rel="stylesheet" />
{% endblock %}

<!-- Main Container Body -->
{% block content %}

<!-- Main post section -->
<section class="container">
    <div class="flex justify-center">
        <!-- Author -->
        <div class="author flex py-8">
            <div class="author-pic-wrapper">
                <img src="{{ post.author.profile_pic.url }}" alt="author-pic-1" class="author-pic rounded-full" />
            </div>
            <div class="author-title-wrapper flex flex-col justify-center px-4">
                <a class="author-title">{{ post.author.first_name }} {{ post.author.last_name }}</a>
                <span class="author-designation">{{ post.author.titles }}</span>
            </div>
        </div>
    </div>

    <!-- Post -->
    <div class="post">
        <h1 class="post-title">
            {{ post.title }}
        </h1>
        <p class="post-subtitle">{{ post.metaTitle }}</p>
        <div class="post-image">
            <img src="{{ post.feature_image.url }}" alt="blog-post-main-image" class="blog-post-main-image" />
        </div>

        <div class="post-content">
            <p>{{ post.content }}</p>
        </div>
    </div>

    <!-- Related Post -->
    <section class="relatedPostSection pt-50">
        <h1 class="relatedPostTitle">Related</h1>

        <div id="relatedPostBody" class="relatedPostBody flex flex-col gap-20 lg:gap-16">
            {% for rlpst in relatedPost %}
            <div class="relatedPostBodyFlex">
                <a href="{% url 'PostApplication:postDetail' rlpst.relatedPost.id rlpst.relatedPost.slug %}">
                    <div class="image flex flex-col justify-start">
                        <img src="{{ rlpst.relatedPost.feature_image.url }}" alt="related-post-pic"
                            class="rounded related-post-pic" />
                    </div>
                </a>
                <div class="info">
                    <div class="cat">
                        <a href="#" class="text-orange-600 hover:text-orange-800">Business, Travel</a>
                        <a href="#" class="text-orange-800 hover:text-orange-600">- March 7, 2024</a>
                    </div>
                    <div class="title">
                        <a href="{% url 'PostApplication:postDetail' rlpst.relatedPost.id rlpst.relatedPost.slug %}"
                            class="title-anchor">{{ rlpst.relatedPost.title }}</a>
                    </div>
                    <div class="author">
                        <img src="{{ rlpst.relatedPost.author.profile_pic.url }}" alt="author-pic-1"
                            class="author-pic rounded-full" />
                        <div class="authorFlex">
                            <a class="author-title text-md font-medium text-gray-800 hover:text-gray-600">
                                {{ rlpst.relatedPost.author.first_name }} {{ rlpst.relatedPost.author.last_name }}
                            </a>
                            <span class="text-xs text-gray-500">{{ rlpst.relatedPost.author.titles }}</span>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
</section>

{% endblock %}